name: Verify WDL updates
on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip3 install miniwdl
      - name: Test with MiniWDL
        run: miniwdl check definitions/*.wdl --suppress CommandShellCheck
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip WDLs
        run: |
          cd definitions/
          zip -r ../workflows.zip . 1> /dev/null
          cd ..
      - name: Commit zipped WDLs
        run: |
          git add workflows.zip
          git commit -m ""
          git push
